package com.example.scanpal.Models;

import java.io.Serializable;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


/**
 * Initializes a user with a username, first name, and last name.
 * Implements Serializable for object serialization and deserialization.
 */
public class User implements Serializable {
    private static final long serialVersionUID = 1L;
    private String username;
    private boolean administrator = false;
    private String firstName;
    private String lastName;
    private String photo; // Profile Photo of the User
    private String deviceToken;
    private String homepage;

    /**
     * Constructs a user with a username, first name, last name, an autogenerated profile picture, and device token.
     *
     * @param username  The username of the user.
     * @param firstName The first name of the user.
     * @param lastName  The last name of the user.
     */
    public User(String username, String firstName, String lastName, String deviceToken) {
        this.username = username;
        this.firstName = firstName;
        this.lastName = lastName;
        this.photo = createProfileImage(username);
        this.deviceToken = deviceToken;
    }

    /**
     * Constructs a user with a username, first name, last name, profile picture, homepage, and device token.
     *
     * @param username  The username of the user.
     * @param firstName The first name of the user.
     * @param lastName  The last name of the user.
     * @param photo     The URL of the user's photo.
     */
    public User(String username, String firstName, String lastName, String photo, String homepage, String deviceToken) {
        this.username = username;
        this.firstName = firstName;
        this.lastName = lastName;
        this.photo = photo;
        this.homepage = homepage;
        this.deviceToken = deviceToken;
    }

    /**
     * Required empty constructor for object serialization.
     */
    public User() {
    }

    /**
     * Generates an MD5 hash of a given string as a hex format.
     *
     * @param input String to hash.
     * @return Hexadecimal string of the MD5 hash.
     * @throws RuntimeException if MD5 algorithm is unavailable.
     */

    public static String md5Hex(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] digest = md.digest(input.getBytes(StandardCharsets.UTF_8));
            return String.format("%032x", new BigInteger(1, digest));
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }


    /**
     * Generates a URL for a default profile image based on the username. This method
     * utilizes Gravatar's service to create a URL pointing to an identicon image,
     * which serves as the user's default profile picture. The resulting image has
     * a size of 100 pixels and is suitable for all audiences (rated PG).
     *
     * @param username The username for which the profile image URL is generated.
     * @return A string representing the URL to the generated default profile image.
     */
    public static String createProfileImage(String username) {
        String hash = md5Hex(username.trim().toLowerCase());
        return "https://www.gravatar.com/avatar/" + hash + "?s=400&d=monsterid&r=pg";
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public boolean isAdministrator() {
        return administrator;
    }

    public void setAdministrator(boolean administrator) {
        this.administrator = administrator;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getDeviceToken() {
        return deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    public String getHomepage() {
        return homepage;
    }

    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }
}
